### ISSUE TITLE
Windows Install Video - Youtube?

### ISSUE THREAD

**Issue by xiongxao** [ducha-aiki/mods#12]
Can you to make a quick step-by-step installation video for Windows and upload it to youtube?  I tried to compile/build it from source using the steps provided with no success.  I'm new to C++, not sure what I'm doing wrong.  If you don't have time and if it's too much to ask for, don't worry about it -but it would be great if you can provide a video :).

**Comment by ducha-aiki** [comment]
Unfortunately, my experience with Windows is very limited and the main version of MODS is Linux one.
However, I will try to do it after CVPR deadline.

**Comment by xiongxao** [comment]
That would be great!  Thanks.

**Comment by ducha-aiki** [comment]
Hi,

I cannot manage to do video, instead, make screenshots of the all parts of installation.
The most of troubles are not related to mods, but installing OpenCV, which was never on Windows, that is why I am using Ubuntu. 

So, Scheme is as in readme
install mingw32 -> write it in the Path. IT IS EXTREMELY IMPORTANT! It is the one of the possible reasons for not finding lapack in process
install cmake
install OpenCV (download 2.4.9 or 2.4.8 -> build with mingw and cmake. VERY IMPORTANT - NOT 2.4.13. 
write OpenCV into Path

compile mods. Because of mingw update, I made some updates to code
Here are screenshots in order of operations


![1](https://user-images.githubusercontent.com/4803565/32984971-c82112cc-ccb8-11e7-926e-ebff207831e3.JPG)
![2](https://user-images.githubusercontent.com/4803565/32984972-c84c7714-ccb8-11e7-95d5-80558a43115e.JPG)
![3](https://user-images.githubusercontent.com/4803565/32984973-c870f850-ccb8-11e7-94ad-0cadb511aab2.JPG)
![4](https://user-images.githubusercontent.com/4803565/32984974-c89452d2-ccb8-11e7-9e8b-bbdc451fbc28.JPG)
![5](https://user-images.githubusercontent.com/4803565/32984975-c8bfff7c-ccb8-11e7-8fcb-f957d41bf693.JPG)
![6](https://user-images.githubusercontent.com/4803565/32984976-c8e4ffca-ccb8-11e7-837c-b1d883dd6318.JPG)
![7](https://user-images.githubusercontent.com/4803565/32984946-c473d01a-ccb8-11e7-96ad-d5984bf55394.JPG)
![8](https://user-images.githubusercontent.com/4803565/32984947-c49c54b8-ccb8-11e7-8730-15aca571a5ea.JPG)
![9](https://user-images.githubusercontent.com/4803565/32984948-c4c5cc8a-ccb8-11e7-840f-7c77bd3b823f.JPG)
![10](https://user-images.githubusercontent.com/4803565/32984949-c4eb95dc-ccb8-11e7-91c8-7b92f44b7d5d.JPG)
![11](https://user-images.githubusercontent.com/4803565/32984950-c50fef36-ccb8-11e7-9a52-7d9afe9e2b0d.JPG)
![12](https://user-images.githubusercontent.com/4803565/32984951-c5343de6-ccb8-11e7-9fb7-1c30b5bc25b2.JPG)
![13](https://user-images.githubusercontent.com/4803565/32984952-c581d826-ccb8-11e7-9046-26e8f2337353.JPG)
![13_2_install_opencv](https://user-images.githubusercontent.com/4803565/32984954-c5a49b86-ccb8-11e7-8cd8-505435b7c855.JPG)
![13_3_install_opencv](https://user-images.githubusercontent.com/4803565/32984955-c5c57f18-ccb8-11e7-8f9c-f0344799e85c.JPG)
![13_4_install_opencv](https://user-images.githubusercontent.com/4803565/32984957-c5e824dc-ccb8-11e7-981a-0fc94cf90746.JPG)
![13_5_install_opencv](https://user-images.githubusercontent.com/4803565/32984958-c60b08a8-ccb8-11e7-989b-7cb04a9ec83a.JPG)
![14](https://user-images.githubusercontent.com/4803565/32984959-c62f58f2-ccb8-11e7-9e92-46c925caf435.JPG)
![15](https://user-images.githubusercontent.com/4803565/32984960-c65ddbe6-ccb8-11e7-817a-b2ad63657cf1.JPG)
![16](https://user-images.githubusercontent.com/4803565/32984961-c6810f4e-ccb8-11e7-8eaf-3e73b758dd39.JPG)
![17](https://user-images.githubusercontent.com/4803565/32984962-c6a58ca2-ccb8-11e7-8000-5bf264171107.JPG)
![18-path](https://user-images.githubusercontent.com/4803565/32984963-c6cace86-ccb8-11e7-834a-b9bdc7e860ed.JPG)
![19](https://user-images.githubusercontent.com/4803565/32984964-c6f90012-ccb8-11e7-97d4-53ff0d2f0cff.JPG)
![20](https://user-images.githubusercontent.com/4803565/32984965-c71fb586-ccb8-11e7-970f-c275bd2f41b6.JPG)
![21](https://user-images.githubusercontent.com/4803565/32984966-c7457870-ccb8-11e7-87e9-5efec9e5605e.JPG)
![opencv-cmake-mods](https://user-images.githubusercontent.com/4803565/32984967-c769f0f6-ccb8-11e7-840d-897a72e127c9.JPG)
![opencv-cmake-mods2](https://user-images.githubusercontent.com/4803565/32984968-c7ababe0-ccb8-11e7-95dc-23b428a28579.JPG)
![opencv-cmake-mods3](https://user-images.githubusercontent.com/4803565/32984969-c7d10f2a-ccb8-11e7-8821-7b0c4b29c692.JPG)
![works](https://user-images.githubusercontent.com/4803565/32984970-c7f3e504-ccb8-11e7-9ebe-585a346bb532.JPG)

**Comment by xiongxao** [comment]
Thank you for the screenshots and your time for putting it together. I will try it. Thanks again.
